language: perl
perl:
  - "5.24"
  - "5.22"
matrix:
  - perl: 5.18
    env: COVERAGE=1
install: cpanm  Getopt::Long Log::Log4perl Pod::Usage Config::Simple Switch HTML::Strip LWP::UserAgent Archive::Extract File::Grep Test::More FindBin HTTP::Server::Brick
