language: perl
perl:
  - "5.24"
  - "5.22"
befor_install: cpanm Devel::Cover::Report::Coveralls
install: cpanm  Getopt::Long Log::Log4perl Pod::Usage Config::Simple Switch HTML::Strip LWP::UserAgent Archive::Extract File::Grep Test::More FindBin HTTP::Server::Brick
script: cover -test -report coveralls
