language: perl
perl:
  - "5.24"
  - "5.22"
install: cpanm  Getopt::Long Log::Log4perl Pod::Usage Config::Simple Switch HTML::Strip LWP::UserAgent Archive::Extract File::Grep Test::More FindBin
script: perl -Mlib=./lib ./buildsrv.pl -c tests/buildsrv.conf &
